[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[target.'cfg(target_os = "dragonos")']
rustflags = [
  "-C", "target-feature=+crt-static",
  "-C", "link-arg=-no-pie",
]